import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { tmpdir } from 'node:os'
import { LocalAdapter } from '../storage/local-adapter'
import type { LibraryLocation } from '../storage/types'
import { isParsableSlicerFile, readGcodeMetadata } from './slicer-metadata-service'

/**
 * The I/O half of reading a sliced file.
 *
 * The parser is tested on strings next door. What matters here is the part that
 * cannot be checked without a real file: that the config block at the very end
 * of a large file is found, and that the megabytes in between are never read.
 */

let root: string
let adapter: LocalAdapter

const library: LibraryLocation = {
  id: '00000000-0000-4000-8000-0000000000ff',
  kind: 'managed',
  backend: 'local',
  allowWrites: false,
  path: '',
}

const CONFIG_BLOCK = [
  '; estimated printing time (normal mode) = 1h 30m 0s',
  '; layer_height = 0.2',
  '; nozzle_diameter = 0.4',
  '; nozzle_type = hardened_steel',
  '; filament_type = PETG',
  '; total filament used [g] = 41.20',
  '',
].join('\n')

beforeEach(async () => {
  root = await mkdtemp(path.join(tmpdir(), 'pb-gcode-'))
  adapter = new LocalAdapter({ ...library, path: root })
})

afterEach(async () => {
  await rm(root, { recursive: true, force: true })
})

async function write(name: string, contents: string): Promise<number> {
  await writeFile(path.join(root, name), contents)
  return Buffer.byteLength(contents)
}

describe('readGcodeMetadata', () => {
  it('reads a small file in one go', async () => {
    const size = await write('small.gcode', `; generated by PrusaSlicer 2.8.0\n${CONFIG_BLOCK}`)

    await expect(readGcodeMetadata(adapter, 'small.gcode', size)).resolves.toMatchObject({
      layerHeightMm: 0.2,
      nozzleMm: 0.4,
      nozzleType: 'hardened_steel',
      material: 'PETG',
      durationMin: 90,
      filamentUsedG: 41.2,
      slicerName: 'PrusaSlicer',
    })
  })

  it('finds the config block at the end of a file far larger than the window', async () => {
    /*
     * The point of the whole module. 4 MB of movement commands is small for a
     * real plate and already many times the 64 KB read window, so a naive
     * head-only read finds the header and misses every setting below.
     */
    const filler = 'G1 X10.0 Y10.0 E0.5\n'.repeat(200_000)
    const size = await write(
      'large.gcode',
      `; generated by PrusaSlicer 2.8.0\n${filler}${CONFIG_BLOCK}`,
    )
    expect(size).toBeGreaterThan(4_000_000)

    const result = await readGcodeMetadata(adapter, 'large.gcode', size)
    expect(result.nozzleType).toBe('hardened_steel')
    expect(result.durationMin).toBe(90)
    // From the header, which proves both ends were read and not just the tail.
    expect(result.slicerName).toBe('PrusaSlicer')
  })

  it('stats the file itself when the caller does not know its size', async () => {
    await write('unsized.gcode', CONFIG_BLOCK)
    await expect(readGcodeMetadata(adapter, 'unsized.gcode', null)).resolves.toMatchObject({
      layerHeightMm: 0.2,
    })
  })

  it('returns nothing for a missing file rather than throwing', async () => {
    // This runs to pre-fill a form; a failure should cost the convenience only.
    await expect(readGcodeMetadata(adapter, 'gone.gcode', 1000)).resolves.toEqual({})
  })

  it('returns nothing for an empty file', async () => {
    const size = await write('empty.gcode', '')
    await expect(readGcodeMetadata(adapter, 'empty.gcode', size)).resolves.toEqual({})
  })
})

describe('isParsableSlicerFile', () => {
  it.each(['gcode', '.gcode', 'GCODE', 'gco', 'g', 'ngc'])('accepts %s', (extension) => {
    expect(isParsableSlicerFile(extension)).toBe(true)
  })

  it.each(['bgcode', '3mf', 'stl', 'ctb', ''])('refuses %s', (extension) => {
    expect(isParsableSlicerFile(extension)).toBe(false)
  })
})
