/**
 * Checks embedded metadata through real HTTP upload and the running worker.
 * Run in the worker's filesystem namespace, with the same DATABASE_URL and
 * BETTER_AUTH_SECRET. No queue or worker is started by this script.
 *
 * VERIFY_BASE_URL=http://localhost:3220 npx tsx scripts/verify-model-imports.mts
 * VERIFY_STORAGE_ROOT can select a directory shared with the worker.
 * VERIFY_KEEP_FIXTURES=1 retains the throwaway account/library for browser checks.
 * VERIFY_CLEANUP_EMAIL=<printed fixture email> removes a retained fixture.
 */
import { createHmac, randomUUID } from 'node:crypto'
import { mkdir, mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { sql } from 'drizzle-orm'
import { strToU8, zipSync } from 'fflate'
import sharp from 'sharp'
import * as tus from 'tus-js-client'
import { loadRootEnv, parseSidecar } from '@pb/core'
import { createDb } from '@pb/db'

loadRootEnv()
const BASE = (process.env.VERIFY_BASE_URL ?? 'http://localhost:3220').replace(/\/$/, '')
const KEEP = process.env.VERIFY_KEEP_FIXTURES === '1'
const RUN = randomUUID()
const LIBRARY_ID = randomUUID()
const EMAIL = `model-import-${RUN}@example.test`
const PASSWORD = `throwaway-${randomUUID()}`
const TITLE = `Metadata Fixture ${RUN}`
const DESIGNER = `Fixture Designer ${RUN}`
const DESCRIPTION = 'Synthetic mounting bracket. - Print flat - No supports'
const normalizeWhitespace = (text: string) => text.replace(/\s+/g, ' ').trim()
const HEADERS = { 'content-type': 'application/json', origin: BASE }
const { db, pool } = createDb()
// Cleanup is deliberately limited to identifiers generated by this verifier.
const cleanupEmail = process.env.VERIFY_CLEANUP_EMAIL
if (cleanupEmail) {
  const match =
    /^model-import-([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})@example\.test$/.exec(
      cleanupEmail,
    )
  if (!match) {
    await pool.end()
    throw new Error('VERIFY_CLEANUP_EMAIL must be a generated fixture email')
  }
  try {
    const fixtureRun = match[1]!
    const libraries = await db.execute<{ id: string; path: string }>(
      sql`SELECT id, path FROM libraries WHERE name = ${`Model Import Fixture ${fixtureRun}`} AND kind = 'managed' AND backend = 'local'`,
    )
    for (const library of libraries.rows) {
      if (
        !path.isAbsolute(library.path) ||
        !path.basename(library.path).startsWith('pb-model-import-')
      ) {
        throw new Error('Refusing to remove an unexpected fixture storage path')
      }
      await db.execute(sql`DELETE FROM libraries WHERE id = ${library.id}`)
      await rm(library.path, { recursive: true, force: true })
    }
    await db.execute(sql`DELETE FROM "user" WHERE email = ${cleanupEmail}`)
    await db.execute(sql`DELETE FROM creators WHERE name = ${`Fixture Designer ${fixtureRun}`}`)
    console.log('Retained verification fixture removed.')
  } finally {
    await pool.end()
  }
  process.exit(0)
}

let root = ''
let modelUrl = ''
let passed = 0
let failed = 0

function check(name: string, ok: boolean) {
  console.log(`${ok ? 'PASS' : 'FAIL'} ${name}`)
  if (ok) passed++
  else failed++
}

async function waitFor<T>(probe: () => Promise<T | null>, label: string): Promise<T> {
  const deadline = Date.now() + 90_000
  while (Date.now() < deadline) {
    const value = await probe()
    if (value !== null) return value
    await new Promise((resolve) => setTimeout(resolve, 750))
  }
  throw new Error(`Timed out waiting for ${label}`)
}

function upload(endpoint: string, bytes: Buffer) {
  return new Promise<void>((resolve, reject) => {
    new tus.Upload(bytes, {
      endpoint: `${BASE}${endpoint}`,
      chunkSize: 256 * 1024,
      retryDelays: [],
      metadata: {
        libraryId: LIBRARY_ID,
        relativePath: 'Fixture Project/project.3mf',
        filename: 'project.3mf',
      },
      onError: reject,
      onSuccess: resolve,
    }).start()
  })
}

async function fixture() {
  const cover = await sharp({
    create: { width: 120, height: 80, channels: 3, background: '#cc8844' },
  })
    .png()
    .toBuffer()
  const entries: Record<string, string | Uint8Array> = {
    '[Content_Types].xml':
      '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/><Default Extension="png" ContentType="image/png"/></Types>',
    '_rels/.rels':
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="m" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel" Target="/3D/3dmodel.model"/><Relationship Id="t" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail" Target="/Auxiliaries/.thumbnails/cover.png"/></Relationships>',
    '3D/3dmodel.model': `<?xml version="1.0"?><model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"><metadata name="Title">${TITLE}</metadata><metadata name="Designer">${DESIGNER}</metadata><metadata name="License">CC0-1.0</metadata><metadata name="CreationDate">2026-07-02</metadata><metadata name="ModificationDate">2026-09-30</metadata><metadata name="Description">&amp;lt;p&amp;gt;Synthetic mounting bracket.&amp;lt;/p&amp;gt;&amp;lt;ul&amp;gt;&amp;lt;li&amp;gt;Print flat&amp;lt;/li&amp;gt;&amp;lt;li&amp;gt;No supports&amp;lt;/li&amp;gt;&amp;lt;/ul&amp;gt;</metadata><resources><object id="1" type="model"><mesh><vertices><vertex x="0" y="0" z="0"/><vertex x="20" y="0" z="0"/><vertex x="0" y="20" z="0"/><vertex x="0" y="0" z="20"/></vertices><triangles><triangle v1="0" v2="2" v3="1"/><triangle v1="0" v2="1" v3="3"/><triangle v1="1" v2="2" v3="3"/><triangle v1="2" v2="0" v3="3"/></triangles></mesh></object></resources><build><item objectid="1"/></build></model>`,
    'Auxiliaries/.thumbnails/cover.png': cover,
  }
  return Buffer.from(
    zipSync(
      Object.fromEntries(
        Object.entries(entries).map(([name, value]) => [
          name,
          typeof value === 'string' ? strToU8(value) : value,
        ]),
      ),
    ),
  )
}

try {
  const secret = process.env.BETTER_AUTH_SECRET
  if (!secret) throw new Error('BETTER_AUTH_SECRET is required')
  const storageRoot = process.env.VERIFY_STORAGE_ROOT ?? tmpdir()
  await mkdir(storageRoot, { recursive: true })
  root = await mkdtemp(path.join(storageRoot, 'pb-model-import-'))

  const signup = await fetch(`${BASE}/api/auth/sign-up/email`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({ name: 'Model Import Verification', email: EMAIL, password: PASSWORD }),
  })
  if (!signup.ok) throw new Error(`Fixture signup failed: HTTP ${signup.status}`)
  await db.execute(sql`UPDATE "user" SET role = 'admin' WHERE email = ${EMAIL}`)
  const signin = await fetch(`${BASE}/api/auth/sign-in/email`, {
    method: 'POST',
    headers: HEADERS,
    body: JSON.stringify({ email: EMAIL, password: PASSWORD }),
  })
  const cookie = signin.headers
    .getSetCookie()
    .map((value) => value.split(';')[0])
    .join('; ')
  if (!signin.ok || !cookie) throw new Error('Fixture sign-in failed')
  check('throwaway account signs in', true)
  const get = (route: string) =>
    fetch(`${BASE}${route}`, { headers: { cookie }, redirect: 'manual' })

  await db.execute(
    sql`INSERT INTO libraries (id, name, kind, backend, path, write_sidecar) VALUES (${LIBRARY_ID}, ${`Model Import Fixture ${RUN}`}, 'managed', 'local', ${root}, true)`,
  )
  const page = await get('/upload')
  const uploadHtml = await page.text()
  check(
    'upload page includes local and MakerWorld imports',
    page.status === 200 &&
      uploadHtml.includes('Import from MakerWorld') &&
      uploadHtml.includes('Drop files or folders here'),
  )

  const bytes = await fixture()
  const expires = Date.now() + 3_600_000
  const token = createHmac('sha256', secret).update(`upload:${LIBRARY_ID}:${expires}`).digest('hex')
  await upload(`/api/upload?library=${LIBRARY_ID}&expires=${expires}&token=${token}`, bytes)
  check('real resumable upload completes', true)
  const stored = await readFile(path.join(root, 'Fixture Project/project.3mf'))
  check('original 3MF bytes are unchanged', stored.equals(bytes))

  const model = await waitFor(async () => {
    const result = await db.execute<{
      id: string
      public_id: string
      name: string
      notes: string
      license: string
      creator: string
      file_id: string
      thumb_state: string
    }>(sql`
      SELECT m.id, m.public_id, m.name, m.notes, m.license, c.name AS creator, f.id AS file_id, f.thumb_state
      FROM models m LEFT JOIN creators c ON c.id = m.creator_id JOIN model_files f ON f.model_id = m.id
      WHERE m.library_id = ${LIBRARY_ID} AND m.embedded_metadata_state = 'done' AND f.thumb_state = 'ok' LIMIT 1`)
    return result.rows[0] ?? null
  }, 'existing worker to index metadata and thumbnail')
  check('embedded title replaces generated name', model.name === TITLE)
  check('embedded designer is linked', model.creator === DESIGNER)
  check('embedded licence is stored', model.license === 'CC0-1.0')
  check(
    'rich description is plain readable text',
    normalizeWhitespace(model.notes).includes(DESCRIPTION) &&
      !/&lt;|<\/?(?:p|ul|li)\b/i.test(model.notes),
  )
  check(
    'source dates retain provenance',
    model.notes.includes('Source file creation date: 2026-07-02') &&
      model.notes.includes('Source file modification date: 2026-09-30'),
  )
  const searchable = await db.execute<{ found: boolean }>(
    sql`SELECT search_vector @@ websearch_to_tsquery('pb_search', 'mounting bracket') AS found FROM models WHERE id = ${model.id}`,
  )
  check('imported description is searchable', searchable.rows[0]?.found === true)
  const sidecarText = await waitFor(
    async () =>
      readFile(path.join(root, 'Fixture Project/.printbench.json'), 'utf8').catch(() => null),
    'metadata sidecar',
  )
  const { data: sidecar } = parseSidecar(sidecarText)
  check(
    'sidecar preserves metadata',
    sidecar?.name === TITLE &&
      sidecar?.creator === DESIGNER &&
      sidecar?.license === 'CC0-1.0' &&
      Boolean(sidecar?.notes && normalizeWhitespace(sidecar.notes).includes(DESCRIPTION)),
  )

  const thumbnail = await get(`/api/files/${model.file_id}/thumb`)
  const thumbnailBytes = Buffer.from(await thumbnail.arrayBuffer())
  check(
    'thumbnail endpoint returns an image',
    thumbnail.status === 200 &&
      thumbnail.headers.get('content-type') === 'image/webp' &&
      thumbnailBytes.length > 0,
  )
  if (thumbnail.status === 200 && thumbnailBytes.length) {
    const pixel = await sharp(thumbnailBytes).resize(1, 1).removeAlpha().raw().toBuffer()
    check(
      'thumbnail uses embedded cover instead of mesh render',
      Math.abs(pixel[0]! - 204) < 12 &&
        Math.abs(pixel[1]! - 136) < 12 &&
        Math.abs(pixel[2]! - 68) < 12,
    )
  }
  modelUrl = `${BASE}/models/${model.public_id}`
  const detail = await get(`/models/${model.public_id}`)
  const html = await detail.text()
  check(
    'detail page renders imported information',
    detail.status === 200 &&
      html.includes(TITLE) &&
      html.includes(DESIGNER) &&
      html.includes('Synthetic mounting bracket.') &&
      html.includes('2026-07-02'),
  )
} catch (error) {
  // Do not print raw transport errors: tus includes signed upload URLs.
  console.error(
    error instanceof Error && !error.message.includes('http')
      ? error.message
      : 'Verification request failed; inspect the isolated server logs.',
  )
  failed++
} finally {
  if (!KEEP) {
    await db.execute(sql`DELETE FROM libraries WHERE id = ${LIBRARY_ID}`)
    await db.execute(sql`DELETE FROM "user" WHERE email = ${EMAIL}`)
    await db.execute(sql`DELETE FROM creators WHERE name = ${DESIGNER}`)
    if (root) await rm(root, { recursive: true, force: true })
  } else {
    console.log(`Fixture login: ${EMAIL}`)
    console.log(`Fixture password: ${PASSWORD}`)
    if (modelUrl) console.log(`Fixture model: ${modelUrl}`)
  }
  await pool.end()
  console.log(`${passed} passed, ${failed} failed`)
  process.exitCode = failed ? 1 : 0
}
